@startuml
skinparam sequenceReferenceBorderColor blue
skinparam sequenceReferenceBackgroundColor red
/' Start UML Class '/
Client << Human >>
/' "Client Web" << Human >> as WebCustomer
"Client PdV" << Human >> as ShopCustomer
WebCustomer -|> Client
ShopCustomer -|> Client'/

Responsable << Human >>
Livreur << Human >>
Pizzaiolo << Human >>

:Point de Vente: << System >> as PDV

/' Effectuer une commande de Pizza '/
(Effectuer une commande de Pizza) as (setOrder)
left to right direction
Client --> (setOrder)
PDV --> (setOrder)

/' Consulter une commande de Pizza '/
(Consulter une commande de Pizza) as (getOrder)
PDV -> (getOrder)
Responsable --> (getOrder)

/' Préparer une commande de Pizza '/
(Préparer une commande de Pizza) as (setPrepare)
Pizzaiolo -> (setPrepare)

/' Effectuer une livraison de Pizza '/
(Effectuer une livraison de Pizza) as (setDelivery)
Livreur -> (setDelivery)

/' Consulter une livraison de Pizza '/
(Consulter une livraison de Pizza) as (getDelivery)
Responsable --> (getDelivery)

/' Effectuer un paiement '/
(Effectuer un paiement) as (setPayment)
Client -> (setPayment)



@enduml