@startuml
/' Start UML Class '/

/' Flow Direction '/
left to right direction

/' Actor and Entity '/
"Admin" << Human >> as A1
"Responsable" << Human >> as R1

/' UseCase Relationship '/
/' Gestion des PDV '/
usecase setPDV as "
    Gère les PDV

    --
    Créé, supprime, archive
    et met à jour.
"
R1 --> (setPDV)

/' Gestion des utilisateurs '/
usecase setUser as "
Gère les utilisateurs

--
Créé, supprime et met à jour.
Attribue les profils (droits)
"
R1 --> (setUser)

/' Gestion des profils utilisateur '/
usecase setProfile as "
Gère les profils utilisateurs

--
Créé, supprime et met à jour.
Gère les droits de chaque profile
"
A1 --> (setProfile)

/' End UML Class '/
@enduml